language: java
jdk: openjdk11

before_install:
  - echo $GPG_SECRET_KEYS_ALT | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST_ALT | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
install:
  mvn --settings .maven.xml install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

## Build and release to maven central
script:
  mvn --settings .maven.xml clean deploy -Prelease -B -U
